// <auto-generated />
using System;
using InvestDashboard.Infrastructure.Persistence.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvestDashboard.Infrastructure.Migrations
{
    [DbContext(typeof(InvestDbContext))]
    partial class InvestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvestDashboard.Domain.Aggregates.MarketData.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_type");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("current_price");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ticker");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("assets", (string)null);

                    b.HasDiscriminator<string>("AssetType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("InvestDashboard.Domain.Aggregates.MarketData.HistoricalPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "Date")
                        .HasDatabaseName("idx_historical_prices_asset_date");

                    b.ToTable("historical_prices", (string)null);
                });

            modelBuilder.Entity("InvestDashboard.Domain.Aggregates.Portfolio.AssetPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("asset_type");

                    b.Property<decimal>("AverageCost")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("average_cost");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("current_price");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("quantity");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ticker");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_cost");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("idx_asset_positions_asset_id");

                    b.HasIndex("PortfolioId")
                        .HasDatabaseName("idx_asset_positions_portfolio_id");

                    b.ToTable("asset_positions", (string)null);
                });

            modelBuilder.Entity("InvestDashboard.Domain.Aggregates.Portfolio.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("balance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_portfolios_user_id");

                    b.ToTable("portfolios", (string)null);
                });

            modelBuilder.Entity("InvestDashboard.Domain.Aggregates.Trading.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<decimal>("BrokerageFee")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("brokerage_fee");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("quantity");

                    b.Property<string>("Ticker")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ticker");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_price");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_transactions_user_id");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("InvestDashboard.Domain.Aggregates.MarketData.CryptoAsset", b =>
                {
                    b.HasBaseType("InvestDashboard.Domain.Aggregates.MarketData.Asset");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("network");

                    b.HasDiscriminator().HasValue("Crypto");
                });

            modelBuilder.Entity("InvestDashboard.Domain.Aggregates.MarketData.FiiAsset", b =>
                {
                    b.HasBaseType("InvestDashboard.Domain.Aggregates.MarketData.Asset");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("segment");

                    b.HasDiscriminator().HasValue("Fii");
                });

            modelBuilder.Entity("InvestDashboard.Domain.Aggregates.MarketData.FixedIncomeAsset", b =>
                {
                    b.HasBaseType("InvestDashboard.Domain.Aggregates.MarketData.Asset");

                    b.Property<string>("Indexer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("indexer");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("interest_rate");

                    b.Property<DateTime>("MaturityDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("maturity_date");

                    b.HasDiscriminator().HasValue("FixedIncome");
                });

            modelBuilder.Entity("InvestDashboard.Domain.Aggregates.MarketData.StockAsset", b =>
                {
                    b.HasBaseType("InvestDashboard.Domain.Aggregates.MarketData.Asset");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sector");

                    b.HasDiscriminator().HasValue("Stock");
                });

            modelBuilder.Entity("InvestDashboard.Domain.Aggregates.MarketData.HistoricalPrice", b =>
                {
                    b.HasOne("InvestDashboard.Domain.Aggregates.MarketData.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvestDashboard.Domain.Aggregates.Portfolio.AssetPosition", b =>
                {
                    b.HasOne("InvestDashboard.Domain.Aggregates.MarketData.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestDashboard.Domain.Aggregates.Portfolio.Portfolio", null)
                        .WithMany("Positions")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvestDashboard.Domain.Aggregates.Trading.Transaction", b =>
                {
                    b.HasOne("InvestDashboard.Domain.Aggregates.MarketData.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("InvestDashboard.Domain.Aggregates.Portfolio.Portfolio", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
